"""Builds the client files for CoA chat emoji from emoji.json.

    python apps/coa-emoji/build.py          regenerate ChatEmojiData.lua, download the art into TGA files and draw the
                                            picker button glyph if it is missing
    python apps/coa-emoji/build.py --check  verify the generated files match emoji.json (no network, no Pillow)

The emoji art is Twemoji (CC-BY 4.0, see NOTICE.md). The button glyph is drawn here and is not Twemoji. Pillow is
only needed to convert or draw art.
"""

import argparse
import io
import json
import math
from pathlib import Path
import re
import sys
import urllib.request

ROOT = Path(__file__).resolve().parent
EMOJI_JSON = ROOT / 'emoji.json'
CLIENT = ROOT / 'client' / 'Interface'
DATA_LUA = CLIENT / 'FrameXML' / 'ChatEmojiData.lua'
TEXTURE_DIR = CLIENT / 'CoAEmoji'
ART_URL = 'https://raw.githubusercontent.com/jdecked/twemoji/v17.0.3/assets/72x72/{}.png'
TEXTURE_SIZE = 64
# The smiley on the picker button sits in the client's own square button frame, so it is drawn in the flat gold of
# the client's chat button icons. It is shown at half its size, which keeps it smooth.
BUTTON_GLYPH = 'button.tga'
GLYPH_SIZE = 32
GLYPH_SUPERSAMPLE = 8
GLYPH_GOLD_TOP, GLYPH_GOLD_BOTTOM, GLYPH_RIM, GLYPH_INK = (240, 206, 42), (192, 156, 10), (120, 88, 0), (56, 36, 0)
NAME = re.compile(r'[a-z0-9_+-]+')
CODEPOINTS = re.compile(r'[0-9a-f]{4,6}(?:-[0-9a-f]{4,6})*')
LUA_HEADER = ('-- Generated by apps/coa-emoji/build.py from emoji.json; edit that file and rebuild.\n'
              '-- Each row is { name, texture file, alias... } in picker order.\n')


def load_emoji():
    entries = json.loads(EMOJI_JSON.read_text(encoding='utf-8'))
    seen_names, seen_codepoints = {}, {}
    for entry in entries:
        names = [entry['name'], *entry.get('aliases', [])]
        for name in names:
            if not NAME.fullmatch(name):
                raise ValueError(f'{name!r}: shortcodes are lowercase letters, digits, _, + and -')
            if name in seen_names:
                raise ValueError(f'{name!r} is used by both {seen_names[name]!r} and {entry["name"]!r}')
            seen_names[name] = entry['name']
        if not CODEPOINTS.fullmatch(entry['codepoints']):
            raise ValueError(f'{entry["name"]!r}: codepoints must be lowercase hex joined by "-"')
        if entry['codepoints'] in seen_codepoints:
            raise ValueError(f'{entry["name"]!r} repeats the art of {seen_codepoints[entry["codepoints"]]!r}')
        seen_codepoints[entry['codepoints']] = entry['name']
    return entries


def render_lua(entries):
    rows = []
    for entry in entries:
        cells = [entry['name'], entry['codepoints'], *entry.get('aliases', [])]
        rows.append('    {' + ', '.join(json.dumps(cell) for cell in cells) + '},\n')
    return LUA_HEADER + 'CHAT_EMOJI_DATA = {\n' + ''.join(rows) + '}\n'


def texture_path(entry):
    return TEXTURE_DIR / (entry['codepoints'] + '.tga')


def glyph_path():
    return TEXTURE_DIR / BUTTON_GLYPH


def png_to_tga(png_bytes):
    from PIL import Image
    image = Image.open(io.BytesIO(png_bytes)).convert('RGBA')
    image = image.resize((TEXTURE_SIZE, TEXTURE_SIZE), Image.LANCZOS)
    output = io.BytesIO()
    image.save(output, 'TGA')
    return output.getvalue()


def mix(start, end, amount):
    amount = min(1.0, max(0.0, amount))
    return tuple(round(start[index] + (end[index] - start[index]) * amount) for index in range(3))


def draw_button_glyph():
    """A gold smiley: a disc that darkens towards the bottom and rim, two eyes and a smile."""
    from PIL import Image, ImageDraw
    size = GLYPH_SIZE * GLYPH_SUPERSAMPLE
    middle, radius = size / 2, size * 0.46
    image = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    pixels = image.load()
    for y in range(size):
        body = mix(GLYPH_GOLD_TOP, GLYPH_GOLD_BOTTOM, (y / size - 0.15) / 0.7)
        for x in range(size):
            distance = math.hypot(x + 0.5 - middle, y + 0.5 - middle) / radius
            if distance <= 1:
                pixels[x, y] = mix(body, GLYPH_RIM, (distance - 0.78) / 0.22) + (255,)
    draw = ImageDraw.Draw(image)
    ink = GLYPH_INK + (255,)
    for side in (-1, 1):
        eye_x, eye_y = middle + side * radius * 0.36, middle - radius * 0.2
        draw.ellipse((eye_x - radius * 0.12, eye_y - radius * 0.2, eye_x + radius * 0.12, eye_y + radius * 0.2),
                     fill=ink)
    smile_radius = radius * 0.58
    draw.arc((middle - smile_radius, middle - smile_radius, middle + smile_radius, middle + smile_radius),
             28, 152, fill=ink, width=round(radius * 0.13))
    for angle in (28, 152):
        end_x = middle + math.cos(math.radians(angle)) * smile_radius
        end_y = middle + math.sin(math.radians(angle)) * smile_radius
        cap = radius * 0.065
        draw.ellipse((end_x - cap, end_y - cap, end_x + cap, end_y + cap), fill=ink)
    output = io.BytesIO()
    image.resize((GLYPH_SIZE, GLYPH_SIZE), Image.LANCZOS).save(output, 'TGA')
    return output.getvalue()


def build(entries):
    TEXTURE_DIR.mkdir(parents=True, exist_ok=True)
    DATA_LUA.parent.mkdir(parents=True, exist_ok=True)
    for entry in entries:
        target = texture_path(entry)
        if target.exists():
            continue
        with urllib.request.urlopen(ART_URL.format(entry['codepoints']), timeout=30) as response:
            target.write_bytes(png_to_tga(response.read()))
        print('wrote', target.relative_to(ROOT))
    # Like the emoji art, an existing file is kept; delete button.tga to redraw it.
    if not glyph_path().exists():
        glyph_path().write_bytes(draw_button_glyph())
        print('wrote', glyph_path().relative_to(ROOT))
    DATA_LUA.write_text(render_lua(entries), encoding='utf-8', newline='\n')


def check(entries):
    problems = []
    if not DATA_LUA.is_file() or DATA_LUA.read_text(encoding='utf-8') != render_lua(entries):
        problems.append(f'{DATA_LUA.relative_to(ROOT)} is out of date; run build.py')
    wanted = {texture_path(entry).name for entry in entries} | {BUTTON_GLYPH}
    present = {path.name for path in TEXTURE_DIR.glob('*.tga')} if TEXTURE_DIR.is_dir() else set()
    problems += [f'missing texture {name}' for name in sorted(wanted - present)]
    problems += [f'texture {name} has no emoji.json entry' for name in sorted(present - wanted)]
    return problems


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true', help='verify instead of building')
    args = parser.parse_args(argv)
    entries = load_emoji()
    if args.check:
        problems = check(entries)
        for problem in problems:
            print(problem, file=sys.stderr)
        return int(bool(problems))
    build(entries)
    return 0


if __name__ == '__main__':
    sys.exit(main())
