// Generated by Tools/Generate-LiveClassResourcePolicy.py; do not edit.
// Source policy: Tools/Data/LiveClassResourcePolicy.json
// Capture SHA256: C0BBF8D1794CC6261AEE26AEC896AE545B7185FC5026E152417058328EC323DA
// Empirically calibrated compatibility value, not official source-code parity.
#ifndef AC_LIVE_CLASS_RESOURCE_POLICY_H
#define AC_LIVE_CLASS_RESOURCE_POLICY_H

#include <cstdint>

namespace LiveClassResourcePolicy
{
inline constexpr float RangerFocusPerSecond = 12.0f;

// Captured normal Starcaller power; explicit shapeshift resources stay native.
constexpr std::uint32_t DefaultPowerForClass(std::uint8_t classId, std::uint32_t dbcPower)
{
    return classId == 26 ? 0 : dbcPower;
}
}

#endif
