// Generated by Tools/Generate-RangerFirstFix.py; do not edit.
// ItemDisplayInfo projectile IDs, NOT creature display IDs or cosmetic source item displays.
#ifndef ASCENSION_AMMUNITION_DATA_H
#define ASCENSION_AMMUNITION_DATA_H

#include <array>
#include <cstdint>

namespace AscensionAmmunition
{
struct Entry
{
    std::uint32_t AppearanceId;
    std::uint32_t ItemDisplayId;
};

inline constexpr std::array<Entry, 43> Entries =
{{
    {2196, 143439}, // Incarnation: Radiant Oathsworn Arrow
    {2201, 143440}, // Incarnation: Auric Oathsworn Arrow
    {2202, 143441}, // Incarnation: Cerulean Oathsworn Arrow
    {2203, 143442}, // Incarnation: Crimson Oathsworn Arrow
    {11715, 136342}, // Incarnation: Arrow of Elven Grace
    {14642, 143443}, // Incarnation: Love Witch's Lovely Arrow
    {14643, 143444}, // Incarnation: Sky Witch's Airy Arrow
    {14644, 143445}, // Incarnation: Twilight Witch's Gothic Arrow
    {19381, 142758}, // Incarnation: Foreststalker's Starshade Arrow
    {19382, 142759}, // Incarnation: Foreststalker's Honeyleaf Arrow
    {19383, 142760}, // Incarnation: Foreststalker's Verdant Arrow
    {19384, 142761}, // Incarnation: Foreststalker's Gloomroot Arrow
    {19385, 142762}, // Incarnation: Foreststalker's Roselight Arrow
    {19386, 142763}, // Incarnation: Foreststalker's Twilightbloom Arrow
    {19387, 142764}, // Incarnation: Foreststalker's Wildroot Arrow
    {19388, 142765}, // Incarnation: Foreststalker's Mistpine Arrow
    {20107, 169026}, // Incarnation: Banshee's Chilling Arrow
    {20108, 169027}, // Incarnation: Banshee's Sickly Arrow
    {20109, 169028}, // Incarnation: Banshee's Grotesque Arrow
    {20110, 169029}, // Incarnation: Banshee's Luminescent Arrow
    {47695, 142747}, // Incarnation: Fire Arrow
    {47696, 142746}, // Incarnation: Ice Arrow
    {47697, 142748}, // Incarnation: Acid Arrow
    {47698, 142749}, // Incarnation: Magic Arrow
    {47879, 142750}, // Incarnation: Stars' Fury Arrow
    {122838, 143425}, // Incarnation: Empowered Cerulean Arrow
    {122839, 143426}, // Incarnation: Empowered Umbral Arrow
    {122840, 143427}, // Incarnation: Empowered Fuchsia Arrow
    {122841, 143428}, // Incarnation: Empowered Violet Arrow
    {122842, 143429}, // Incarnation: Empowered Crimsonflare Arrow
    {122843, 143430}, // Incarnation: Empowered Viridian Arrow
    {122844, 143431}, // Incarnation: Empowered Aureate Arrow
    {122845, 143432}, // Incarnation: Eagletalon Arrow
    {122846, 143433}, // Incarnation: Vicious Eagletalon Arrow
    {122847, 143434}, // Incarnation: Verdant Eagletalon Arrow
    {122848, 143435}, // Incarnation: Azure Eagletalon Arrow
    {122849, 143436}, // Incarnation: Ruddy Eagletalon Arrow
    {122850, 143437}, // Incarnation: Savage Eagletalon Arrow
    {122851, 143438}, // Incarnation: Feral Eagletalon Arrow
    {233197, 142751}, // Incarnation: Sunny Blossom Arrow
    {233198, 142752}, // Incarnation: Orchid Blossom Arrow
    {233199, 142753}, // Incarnation: Lavender Blossom Arrow
    {233270, 142705}, // Incarnation: Dark Ranger General's Arrow
}};
}

#endif
