-- Current Runemaster Echoes of Eternity: ordinary Zenith replacement and shared debt.
-- Generated by tools/Generate-RunemasterEchoes.py; existing Zenith activation bindings stay.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` IN (712325, 712389) AND `ScriptName` = 'spell_ascension_runemaster_echoes';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(712325, 'spell_ascension_runemaster_echoes'),
(712389, 'spell_ascension_runemaster_echoes');
COMMIT;
