-- Generated by tools/Generate-WitchHunterFlourish.py; policy version1.
START TRANSACTION;
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 805365 AND `spell_effect` = 807637 AND `type` = 2;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
(805365, 807637, 2, 'Local CoA Flourish: owned periodic aura follows the main buff');
DELETE FROM `spell_bonus_data` WHERE `entry` = 807762;
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(807762, 0, 0, 1, 0, 'Local CoA Flourish: each pulse uses 100% melee AP and no SP');
COMMIT;
