-- Generated by tools/Generate-WitchHunterSpellPower.py; policy version1.
START TRANSACTION;
DELETE FROM `spell_bonus_data` WHERE `entry` IN (802140, 803366, 803367, 803368, 803369);
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(802140, 1, 0, 0.4, 0, 'Local CoA Fiery Judgement rank1: 100% fire SP and40% melee AP'),
(803366, 1, 0, 0.55, 0, 'Local CoA Fiery Judgement rank2: 100% fire SP and55% melee AP'),
(803367, 1, 0, 0.55, 0, 'Local CoA Fiery Judgement rank3: 100% fire SP and55% melee AP'),
(803368, 1, 0, 0.55, 0, 'Local CoA Fiery Judgement rank4: 100% fire SP and55% melee AP'),
(803369, 1, 0, 0.55, 0, 'Local CoA Fiery Judgement rank5: 100% fire SP and55% melee AP');
COMMIT;
