-- Generated by tools/Generate-TinkerCombatSymbiosis.py; policy version 1.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = 805305 AND `ScriptName` = 'aura_ascension_tinker_combat_symbiosis';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(805305, 'aura_ascension_tinker_combat_symbiosis');
DELETE FROM `spell_proc` WHERE `SpellId` = 805305;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(805305, 0, 0, 0, 0, 0, 349524, 1, 2, 3, 2, 3, 0, 100, 0, 20);
COMMIT;
