-- Generated by tools/Generate-WitchHunterTorchlight.py; policy version1.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = 503662 AND `ScriptName` = 'spell_ascension_witch_hunter_torchlight_mark';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(503662, 'spell_ascension_witch_hunter_torchlight_mark');
DELETE FROM `spell_proc` WHERE `SpellId` = 503662;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(503662, 0, 0, 0, 0, 0, 139944, 1, 0, 0, 256, 0, 0, 100, 0, 5);
DELETE FROM `spell_bonus_data` WHERE `entry` = 503662;
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(503662, 0.45, 0, 0.3, 0, 'Local CoA Torchlight: 45% fire SP and 30% melee AP');
COMMIT;
