-- Generated by tools/Generate-TinkerHacking.py; policy version 1.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = 705796 AND `ScriptName` = 'aura_ascension_tinker_hacking';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(705796, 'aura_ascension_tinker_hacking');
COMMIT;
