-- Generated by tools/Generate-PrimalistKingMountain.py; source-only candidate.
-- Native aura ownership supplies 30% Stamina AP while King of the Mountain is active.
START TRANSACTION;
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 570183 AND `spell_effect` = 570270 AND `type` = 2;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
(570183, 570270, 2, 'Local Primalist: King of the Mountain Stamina attack power');
COMMIT;
