-- Generated by Tools/Generate-CoAProcCooldowns.py; do not edit.
--
-- CoA expresses a proc's internal cooldown as a cooldown on the proc carrier itself. An aura that
-- cannot be cast has no other use for one, and the values read exactly like internal cooldowns:
-- 4, 15, 30, 60, 120, 180 and 300 seconds. AzerothCore never consults that field for a proc -
-- SpellProcEntry::Cooldown is the only rate limiter the proc system has - so these fired on every
-- qualifying event, and 20 of the 25 are 100% chance carriers where the cooldown is the
-- entire rate limit.
--
-- The set is narrow on purpose: a castable ability's cooldown belongs to the cast and says nothing
-- about its proc, so a row is taken only when the spell has no resource cost, no cast time, no
-- castable effect and does carry a proc aura. That rejects 35 spells that pay a resource,
-- 2 with a castable effect and 1 with no proc aura.
--
-- 25 spells; set digest 7C9AD1358A7C4395.
START TRANSACTION;
UPDATE `spell_proc` SET `Cooldown` = 60000 WHERE `SpellId` = 503851; -- Contagion: 60s, client chance 30%
UPDATE `spell_proc` SET `Cooldown` = 60000 WHERE `SpellId` = 524920; -- Burning Blade: 60s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 15000 WHERE `SpellId` = 573064; -- Ale of The God-King: 15s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 15000 WHERE `SpellId` = 573224; -- Ale of The God-King: 15s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 15000 WHERE `SpellId` = 573225; -- Ale of The God-King: 15s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 30000 WHERE `SpellId` = 704777; -- Infused Aegis: 30s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 180000 WHERE `SpellId` = 706021; -- Mycelial Replenishment: 180s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 180000 WHERE `SpellId` = 800892; -- Harden: 180s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 180000 WHERE `SpellId` = 801441; -- Libram of Consecration: 180s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 180000 WHERE `SpellId` = 801463; -- Libram of Grace: 180s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 180000 WHERE `SpellId` = 801466; -- Libram of Zeal: 180s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 30000 WHERE `SpellId` = 801482; -- Downfall: 30s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 30000 WHERE `SpellId` = 801483; -- Redemption: 30s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 120000 WHERE `SpellId` = 801549; -- Thick Skull: 120s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 120000 WHERE `SpellId` = 801774; -- Hero's March: 120s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 180000 WHERE `SpellId` = 802188; -- Counter Stance: 180s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 120000 WHERE `SpellId` = 802276; -- Vampiric Tonic: 120s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 4000 WHERE `SpellId` = 802604; -- Pestilence of War: 4s, client chance 20%
UPDATE `spell_proc` SET `Cooldown` = 180000 WHERE `SpellId` = 803524; -- Hero's March: 180s, client chance 5%
UPDATE `spell_proc` SET `Cooldown` = 60000 WHERE `SpellId` = 803904; -- Annihilation: 60s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 60000 WHERE `SpellId` = 804141; -- Berserker: 60s, client chance 20%
UPDATE `spell_proc` SET `Cooldown` = 120000 WHERE `SpellId` = 805439; -- Shadowsong's Mandate: 120s, client chance 40%
UPDATE `spell_proc` SET `Cooldown` = 15000 WHERE `SpellId` = 805780; -- Ale of The God-King: 15s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 120000 WHERE `SpellId` = 805804; -- Ramhorn Rage: 120s, client chance 100%
UPDATE `spell_proc` SET `Cooldown` = 300000 WHERE `SpellId` = 805884; -- Extraction: 300s, client chance 100%
COMMIT;
