-- Generated by tools/Generate-PrimalistEarthshaping.py; source-only candidate.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = 680441 AND `ScriptName` = 'spell_ascension_primalist_earthshaping';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (680441, 'spell_ascension_primalist_earthshaping');
DELETE FROM `spell_script_names` WHERE `spell_id` = 680439 AND `ScriptName` = 'spell_ascension_primalist_therazane_update';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (680439, 'spell_ascension_primalist_therazane_update');
COMMIT;
