-- Generated by tools/Generate-WitchHunterTorch.py; policy version1.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = 560226 AND `ScriptName` = 'spell_ascension_witch_hunter_torch_stacks';
DELETE FROM `spell_script_names` WHERE `spell_id` = 802277 AND `ScriptName` = 'spell_ascension_witch_hunter_pyro_torchlight';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(560226, 'spell_ascension_witch_hunter_torch_stacks'),
(802277, 'spell_ascension_witch_hunter_pyro_torchlight');
DELETE FROM `spell_proc` WHERE `SpellId` = 560226;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(560226, 4, 21, 0, 0, 16384, 65536, 1, 2, 0, 2, 0, 0, 100, 0, 0);
COMMIT;
