-- Generated by tools/Generate-VenomancerVenoms.py; policy version 1.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = 630868 AND `ScriptName` = 'spell_ascension_venomancer_venom_selection';
DELETE FROM `spell_script_names` WHERE `spell_id` = 630868 AND `ScriptName` = 'aura_ascension_venomancer_venom_selection';
DELETE FROM `spell_script_names` WHERE `spell_id` = 805731 AND `ScriptName` = 'spell_ascension_venomancer_venom_selection';
DELETE FROM `spell_script_names` WHERE `spell_id` = 805731 AND `ScriptName` = 'aura_ascension_venomancer_venom_selection';
DELETE FROM `spell_script_names` WHERE `spell_id` = 805775 AND `ScriptName` = 'spell_ascension_venomancer_venom_selection';
DELETE FROM `spell_script_names` WHERE `spell_id` = 805775 AND `ScriptName` = 'aura_ascension_venomancer_venom_selection';
DELETE FROM `spell_script_names` WHERE `spell_id` = 805776 AND `ScriptName` = 'spell_ascension_venomancer_venom_selection';
DELETE FROM `spell_script_names` WHERE `spell_id` = 805776 AND `ScriptName` = 'aura_ascension_venomancer_venom_selection';
DELETE FROM `spell_script_names` WHERE `spell_id` = 805777 AND `ScriptName` = 'spell_ascension_venomancer_venom_selection';
DELETE FROM `spell_script_names` WHERE `spell_id` = 805777 AND `ScriptName` = 'aura_ascension_venomancer_venom_selection';
DELETE FROM `spell_script_names` WHERE `spell_id` = 805778 AND `ScriptName` = 'spell_ascension_venomancer_venom_selection';
DELETE FROM `spell_script_names` WHERE `spell_id` = 805778 AND `ScriptName` = 'aura_ascension_venomancer_venom_selection';
DELETE FROM `spell_script_names` WHERE `spell_id` = 630872 AND `ScriptName` = 'spell_ascension_venomancer_remove_venoms';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(630868, 'spell_ascension_venomancer_venom_selection'),
(630868, 'aura_ascension_venomancer_venom_selection'),
(805731, 'spell_ascension_venomancer_venom_selection'),
(805731, 'aura_ascension_venomancer_venom_selection'),
(805775, 'spell_ascension_venomancer_venom_selection'),
(805775, 'aura_ascension_venomancer_venom_selection'),
(805776, 'spell_ascension_venomancer_venom_selection'),
(805776, 'aura_ascension_venomancer_venom_selection'),
(805777, 'spell_ascension_venomancer_venom_selection'),
(805777, 'aura_ascension_venomancer_venom_selection'),
(805778, 'spell_ascension_venomancer_venom_selection'),
(805778, 'aura_ascension_venomancer_venom_selection'),
(630872, 'spell_ascension_venomancer_remove_venoms');
COMMIT;
