-- Generated by tools/Generate-RangerSkullpiercer.py; policy version 1.
-- Requires AscensionRangerScaling.cpp; negative spell ID binds all ten native ranks.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = -802036 AND `ScriptName` = 'spell_ascension_ranger_skullpiercer';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(-802036, 'spell_ascension_ranger_skullpiercer');
COMMIT;
