-- Generated by Tools/Audit-LocalChangelog.py; reviewed CoA changelog coefficients only.
-- 20260831-coa-changelog-v1. Do not replace applied migrations; create a new revision for later changes.
-- No character, ownership, profession, talent, proficiency or client data is modified.
START TRANSACTION;

-- guardian-ram-ap; archive note(s): 69620.
DELETE FROM `spell_bonus_data` WHERE `entry` IN (573204, 573205, 573206, 573207, 573208, 573209, 573210, 573211, 802284);
INSERT INTO `spell_bonus_data`
    (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`)
VALUES
    (573204, 0, 0, 0.42, 0, 'CoA changelog 69620 - Ram'),
    (573205, 0, 0, 0.42, 0, 'CoA changelog 69620 - Ram'),
    (573206, 0, 0, 0.42, 0, 'CoA changelog 69620 - Ram'),
    (573207, 0, 0, 0.42, 0, 'CoA changelog 69620 - Ram'),
    (573208, 0, 0, 0.42, 0, 'CoA changelog 69620 - Ram'),
    (573209, 0, 0, 0.42, 0, 'CoA changelog 69620 - Ram'),
    (573210, 0, 0, 0.42, 0, 'CoA changelog 69620 - Ram'),
    (573211, 0, 0, 0.42, 0, 'CoA changelog 69620 - Ram'),
    (802284, 0, 0, 0.42, 0, 'CoA changelog 69620 - Ram');

-- guardian-pulverize-ap; archive note(s): 69621.
DELETE FROM `spell_bonus_data` WHERE `entry` IN (573286, 573292, 800311, 802439, 802440, 802441, 802442, 802443);
INSERT INTO `spell_bonus_data`
    (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`)
VALUES
    (573286, 0, 0, 0.4, 0, 'CoA changelog 69621 - Pulverize'),
    (573292, 0, 0, 0.4, 0, 'CoA changelog 69621 - Pulverize'),
    (800311, 0, 0, 0.4, 0, 'CoA changelog 69621 - Pulverize'),
    (802439, 0, 0, 0.4, 0, 'CoA changelog 69621 - Pulverize'),
    (802440, 0, 0, 0.4, 0, 'CoA changelog 69621 - Pulverize'),
    (802441, 0, 0, 0.4, 0, 'CoA changelog 69621 - Pulverize'),
    (802442, 0, 0, 0.4, 0, 'CoA changelog 69621 - Pulverize'),
    (802443, 0, 0, 0.4, 0, 'CoA changelog 69621 - Pulverize');

-- guardian-spear-throw-ap; archive note(s): 69630.
DELETE FROM `spell_bonus_data` WHERE `entry` IN (500463, 572142, 572143, 572144, 572145, 572146, 572147);
INSERT INTO `spell_bonus_data`
    (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`)
VALUES
    (500463, 0, 0, 0.665, 0, 'CoA changelog 69630 - Spear Throw'),
    (572142, 0, 0, 0.665, 0, 'CoA changelog 69630 - Spear Throw'),
    (572143, 0, 0, 0.665, 0, 'CoA changelog 69630 - Spear Throw'),
    (572144, 0, 0, 0.665, 0, 'CoA changelog 69630 - Spear Throw'),
    (572145, 0, 0, 0.665, 0, 'CoA changelog 69630 - Spear Throw'),
    (572146, 0, 0, 0.665, 0, 'CoA changelog 69630 - Spear Throw'),
    (572147, 0, 0, 0.665, 0, 'CoA changelog 69630 - Spear Throw');

-- witch-hunter-tormentor-rap; archive note(s): 71856.
DELETE FROM `spell_bonus_data` WHERE `entry` IN (501344, 501345, 501346, 501347, 501348, 501349, 501350, 501351, 501352, 501353, 501354, 501355, 800162);
INSERT INTO `spell_bonus_data`
    (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`)
VALUES
    (501344, 0.175, 0, 0, 0.295, 'CoA changelog 71856 - Tormentor'),
    (501345, 0.175, 0, 0, 0.295, 'CoA changelog 71856 - Tormentor'),
    (501346, 0.175, 0, 0, 0.295, 'CoA changelog 71856 - Tormentor'),
    (501347, 0.175, 0, 0, 0.295, 'CoA changelog 71856 - Tormentor'),
    (501348, 0.175, 0, 0, 0.295, 'CoA changelog 71856 - Tormentor'),
    (501349, 0.175, 0, 0, 0.295, 'CoA changelog 71856 - Tormentor'),
    (501350, 0.175, 0, 0, 0.295, 'CoA changelog 71856 - Tormentor'),
    (501351, 0.175, 0, 0, 0.295, 'CoA changelog 71856 - Tormentor'),
    (501352, 0.175, 0, 0, 0.295, 'CoA changelog 71856 - Tormentor'),
    (501353, 0.175, 0, 0, 0.295, 'CoA changelog 71856 - Tormentor'),
    (501354, 0.175, 0, 0, 0.295, 'CoA changelog 71856 - Tormentor'),
    (501355, 0.175, 0, 0, 0.295, 'CoA changelog 71856 - Tormentor'),
    (800162, 0.175, 0, 0, 0.295, 'CoA changelog 71856 - Tormentor');

COMMIT;
