-- Generated by tools/Generate-ReaperDirge.py; source-only candidate.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = 801328 AND `ScriptName` = 'spell_ascension_reaper_dirge_weapons';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (801328, 'spell_ascension_reaper_dirge_weapons');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803834 AND `ScriptName` = 'spell_ascension_reaper_dirge_weapons';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803834, 'spell_ascension_reaper_dirge_weapons');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803835 AND `ScriptName` = 'spell_ascension_reaper_dirge_weapons';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803835, 'spell_ascension_reaper_dirge_weapons');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803836 AND `ScriptName` = 'spell_ascension_reaper_dirge_weapons';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803836, 'spell_ascension_reaper_dirge_weapons');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803837 AND `ScriptName` = 'spell_ascension_reaper_dirge_weapons';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803837, 'spell_ascension_reaper_dirge_weapons');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803838 AND `ScriptName` = 'spell_ascension_reaper_dirge_weapons';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803838, 'spell_ascension_reaper_dirge_weapons');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803839 AND `ScriptName` = 'spell_ascension_reaper_dirge_weapons';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803839, 'spell_ascension_reaper_dirge_weapons');
DELETE FROM `spell_script_names` WHERE `spell_id` = 801311 AND `ScriptName` = 'spell_ascension_reaper_dirge_dagger';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (801311, 'spell_ascension_reaper_dirge_dagger');
COMMIT;
