-- Generated by tools/Generate-WitchHunterTonicProcs.py; policy version1.
START TRANSACTION;
DELETE FROM `spell_proc` WHERE `SpellId` IN (705528, 705533);
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(705528, 0, 21, 0, 0, 512, 81920, 7, 4, 0, 0, 0, 0, 100, 0, 0),
(705533, 0, 21, 0, 0, 512, 81920, 7, 4, 0, 0, 0, 0, 100, 0, 0);
COMMIT;
