-- Generated by tools/Generate-TinkerAugmentationTalents.py; policy version 1.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = 801821 AND `ScriptName` = 'aura_ascension_tinker_augmentor';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(801821, 'aura_ascension_tinker_augmentor');
DELETE FROM `spell_script_names` WHERE `spell_id` = 807531 AND `ScriptName` = 'aura_ascension_tinker_stim_pack';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(807531, 'aura_ascension_tinker_stim_pack');
DELETE FROM `spell_script_names` WHERE `spell_id` = 653255 AND `ScriptName` = 'spell_ascension_tinker_stim_cooldown';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(653255, 'spell_ascension_tinker_stim_cooldown');
DELETE FROM `spell_script_names` WHERE `spell_id` = 807748 AND `ScriptName` = 'aura_ascension_tinker_cybernetic';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(807748, 'aura_ascension_tinker_cybernetic');
DELETE FROM `spell_script_names` WHERE `spell_id` = 653283 AND `ScriptName` = 'aura_ascension_tinker_cybernetic_shield';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(653283, 'aura_ascension_tinker_cybernetic_shield');
DELETE FROM `spell_proc` WHERE `SpellId` IN (807531, 807748);
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(807531, 0, 34, 128, 0, 0, 16384, 2, 2, 3, 2, 0, 0, 100, 0, 0),
(807748, 0, 34, 128, 0, 0, 16384, 2, 2, 3, 2, 0, 0, 100, 0, 0);
COMMIT;
