-- Generated by tools/Generate-TinkerCombustion.py; source-only candidate.
-- Exact helper uses guarded native ranged AP source metadata.
START TRANSACTION;
DELETE FROM `spell_bonus_data` WHERE `entry` = 801388;
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(801388, 0, 0, 0.2, 0, 'Local Tinker: Mechsuit Combustion ranged AP');
COMMIT;
