-- Generated by tools/Generate-PrimalistSpiritBeast.py; source-only candidate.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = 574301 AND `ScriptName` = 'spell_ascension_primalist_harness';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (574301, 'spell_ascension_primalist_harness');
DELETE FROM `spell_script_names` WHERE `spell_id` = 574304 AND `ScriptName` = 'spell_ascension_primalist_harness_tame';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (574304, 'spell_ascension_primalist_harness_tame');
COMMIT;
