-- Generated by tools/Generate-RunemasterZenith.py; pinned current Runelord formula.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `ScriptName` IN ('spell_ascension_runemaster_zenith', 'spell_ascension_runemaster_runelord_damage');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(712325, 'spell_ascension_runemaster_zenith'),
(712389, 'spell_ascension_runemaster_zenith'),
(806997, 'spell_ascension_runemaster_runelord_damage');
DELETE FROM `spell_bonus_data` WHERE `entry` = 806997;
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(806997, 0, 0, 0.33, 0, 'Runelord: current visible .33 melee AP, no SP');
COMMIT;
