-- Generated by tools/Generate-WitchHunterTonicSupply.py; policy version1.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_ascension_witch_hunter_tonic_supply' AND `spell_id` IN (-680491, 802276, 802277, 802278, -802279, 802826);
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(-680491, 'spell_ascension_witch_hunter_tonic_supply'),
(802276, 'spell_ascension_witch_hunter_tonic_supply'),
(802277, 'spell_ascension_witch_hunter_tonic_supply'),
(802278, 'spell_ascension_witch_hunter_tonic_supply'),
(-802279, 'spell_ascension_witch_hunter_tonic_supply'),
(802826, 'spell_ascension_witch_hunter_tonic_supply');
COMMIT;
