-- Generated by Tools/Generate-LocalSpellProgression.py; verified CoA level-rank chains only.
-- No character spells or talent choices are modified by this migration.
START TRANSACTION;
DELETE FROM `spell_ranks` WHERE `first_spell_id` IN (500124);
INSERT INTO `spell_ranks` (`first_spell_id`, `spell_id`, `rank`) VALUES
(500124, 500124, 1),
(500124, 501680, 2),
(500124, 501681, 3),
(500124, 501682, 4),
(500124, 501683, 5);
COMMIT;
