-- Generated by Tools/Generate-LocalClassStarters.py --write; do not edit.
-- Only local generated creation rosters change; existing characters and item templates are untouched.
START TRANSACTION;
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 12 AND `Note` = 'Ascension Barbarian starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 12, 2000000, 1, 'Ascension Barbarian starter kit'),
(0, 12, 2000001, 1, 'Ascension Barbarian starter kit'),
(0, 12, 2000002, 1, 'Ascension Barbarian starter kit'),
(0, 12, 12282, 1, 'Ascension Barbarian starter kit'),
(0, 12, 357876, 1, 'Ascension Barbarian starter kit'),
(0, 12, 6948, 1, 'Ascension Barbarian starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 13 AND `Note` = 'Ascension WitchDoctor starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 13, 2000011, 1, 'Ascension WitchDoctor starter kit'),
(0, 13, 484330, 1, 'Ascension WitchDoctor starter kit'),
(0, 13, 2000013, 1, 'Ascension WitchDoctor starter kit'),
(0, 13, 629945, 1, 'Ascension WitchDoctor starter kit'),
(0, 13, 2000014, 1, 'Ascension WitchDoctor starter kit'),
(0, 13, 6948, 1, 'Ascension WitchDoctor starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 14 AND `Note` = 'Ascension DemonHunter starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 14, 2000007, 1, 'Ascension DemonHunter starter kit'),
(0, 14, 2000008, 1, 'Ascension DemonHunter starter kit'),
(0, 14, 2000009, 1, 'Ascension DemonHunter starter kit'),
(0, 14, 629940, 1, 'Ascension DemonHunter starter kit'),
(0, 14, 6948, 1, 'Ascension DemonHunter starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 15 AND `Note` = 'Ascension WitchHunter starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 15, 2000015, 1, 'Ascension WitchHunter starter kit'),
(0, 15, 2000016, 1, 'Ascension WitchHunter starter kit'),
(0, 15, 2000018, 1, 'Ascension WitchHunter starter kit'),
(0, 15, 2092, 1, 'Ascension WitchHunter starter kit'),
(0, 15, 2149641, 1, 'Ascension WitchHunter starter kit'),
(0, 15, 2000017, 1, 'Ascension WitchHunter starter kit'),
(0, 15, 6948, 1, 'Ascension WitchHunter starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 16 AND `Note` = 'Ascension Stormbringer starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 16, 2000019, 1, 'Ascension Stormbringer starter kit'),
(0, 16, 2000020, 1, 'Ascension Stormbringer starter kit'),
(0, 16, 2000021, 1, 'Ascension Stormbringer starter kit'),
(0, 16, 682734, 1, 'Ascension Stormbringer starter kit'),
(0, 16, 501973, 1, 'Ascension Stormbringer starter kit'),
(0, 16, 6948, 1, 'Ascension Stormbringer starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 17 AND `Note` = 'Ascension KnightOfXoroth starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 17, 2000022, 1, 'Ascension KnightOfXoroth starter kit'),
(0, 17, 2000023, 1, 'Ascension KnightOfXoroth starter kit'),
(0, 17, 2000024, 1, 'Ascension KnightOfXoroth starter kit'),
(0, 17, 629951, 1, 'Ascension KnightOfXoroth starter kit'),
(0, 17, 6948, 1, 'Ascension KnightOfXoroth starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 18 AND `Note` = 'Ascension Guardian starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 18, 2000025, 1, 'Ascension Guardian starter kit'),
(0, 18, 2000026, 1, 'Ascension Guardian starter kit'),
(0, 18, 2000027, 1, 'Ascension Guardian starter kit'),
(0, 18, 629951, 1, 'Ascension Guardian starter kit'),
(0, 18, 629929, 1, 'Ascension Guardian starter kit'),
(0, 18, 244613, 1, 'Ascension Guardian starter kit'),
(0, 18, 6948, 1, 'Ascension Guardian starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 19 AND `Note` = 'Ascension Monk starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 19, 2000028, 1, 'Ascension Monk starter kit'),
(0, 19, 2117000, 1, 'Ascension Monk starter kit'),
(0, 19, 2000030, 1, 'Ascension Monk starter kit'),
(0, 19, 629941, 1, 'Ascension Monk starter kit'),
(0, 19, 2446130, 1, 'Ascension Monk starter kit'),
(0, 19, 6948, 1, 'Ascension Monk starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 20 AND `Note` = 'Ascension SonOfArugal starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 20, 2000031, 1, 'Ascension SonOfArugal starter kit'),
(0, 20, 494334, 1, 'Ascension SonOfArugal starter kit'),
(0, 20, 2000033, 1, 'Ascension SonOfArugal starter kit'),
(0, 20, 629942, 1, 'Ascension SonOfArugal starter kit'),
(0, 20, 6948, 1, 'Ascension SonOfArugal starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 21 AND `Note` = 'Ascension Ranger starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 21, 2000038, 1, 'Ascension Ranger starter kit'),
(0, 21, 2000039, 1, 'Ascension Ranger starter kit'),
(0, 21, 2000040, 1, 'Ascension Ranger starter kit'),
(0, 21, 2092, 1, 'Ascension Ranger starter kit'),
(0, 21, 484322, 1, 'Ascension Ranger starter kit'),
(0, 21, 6948, 1, 'Ascension Ranger starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 22 AND `Note` = 'Ascension Chronomancer starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 22, 494335, 1, 'Ascension Chronomancer starter kit'),
(0, 22, 2000045, 1, 'Ascension Chronomancer starter kit'),
(0, 22, 2000046, 1, 'Ascension Chronomancer starter kit'),
(0, 22, 629948, 1, 'Ascension Chronomancer starter kit'),
(0, 22, 6948, 1, 'Ascension Chronomancer starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 23 AND `Note` = 'Ascension Necromancer starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 23, 2000051, 1, 'Ascension Necromancer starter kit'),
(0, 23, 2000052, 1, 'Ascension Necromancer starter kit'),
(0, 23, 2000053, 1, 'Ascension Necromancer starter kit'),
(0, 23, 629950, 1, 'Ascension Necromancer starter kit'),
(0, 23, 6948, 1, 'Ascension Necromancer starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 24 AND `Note` = 'Ascension Pyromancer starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 24, 2000054, 1, 'Ascension Pyromancer starter kit'),
(0, 24, 2000055, 1, 'Ascension Pyromancer starter kit'),
(0, 24, 2000056, 1, 'Ascension Pyromancer starter kit'),
(0, 24, 484327, 1, 'Ascension Pyromancer starter kit'),
(0, 24, 6948, 1, 'Ascension Pyromancer starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 25 AND `Note` = 'Ascension Cultist starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 25, 2000057, 1, 'Ascension Cultist starter kit'),
(0, 25, 484331, 1, 'Ascension Cultist starter kit'),
(0, 25, 2000059, 1, 'Ascension Cultist starter kit'),
(0, 25, 629982, 1, 'Ascension Cultist starter kit'),
(0, 25, 6948, 1, 'Ascension Cultist starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 26 AND `Note` = 'Ascension Starcaller starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 26, 2000060, 1, 'Ascension Starcaller starter kit'),
(0, 26, 2000061, 1, 'Ascension Starcaller starter kit'),
(0, 26, 2000062, 1, 'Ascension Starcaller starter kit'),
(0, 26, 2000004, 1, 'Ascension Starcaller starter kit'),
(0, 26, 6948, 1, 'Ascension Starcaller starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 27 AND `Note` = 'Ascension SunCleric starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 27, 2000063, 1, 'Ascension SunCleric starter kit'),
(0, 27, 2000064, 1, 'Ascension SunCleric starter kit'),
(0, 27, 2000065, 1, 'Ascension SunCleric starter kit'),
(0, 27, 629944, 1, 'Ascension SunCleric starter kit'),
(0, 27, 6948, 1, 'Ascension SunCleric starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 28 AND `Note` = 'Ascension Tinker starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 28, 2000041, 1, 'Ascension Tinker starter kit'),
(0, 28, 2000042, 1, 'Ascension Tinker starter kit'),
(0, 28, 2000043, 1, 'Ascension Tinker starter kit'),
(0, 28, 2000048, 1, 'Ascension Tinker starter kit'),
(0, 28, 484364, 1, 'Ascension Tinker starter kit'),
(0, 28, 2000047, 1, 'Ascension Tinker starter kit'),
(0, 28, 6948, 1, 'Ascension Tinker starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 29 AND `Note` = 'Ascension Venomancer starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 29, 967757, 1, 'Ascension Venomancer starter kit'),
(0, 29, 2000067, 1, 'Ascension Venomancer starter kit'),
(0, 29, 2000068, 1, 'Ascension Venomancer starter kit'),
(0, 29, 629982, 1, 'Ascension Venomancer starter kit'),
(0, 29, 6948, 1, 'Ascension Venomancer starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 30 AND `Note` = 'Ascension Reaper starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 30, 2000069, 1, 'Ascension Reaper starter kit'),
(0, 30, 2000070, 1, 'Ascension Reaper starter kit'),
(0, 30, 2000071, 1, 'Ascension Reaper starter kit'),
(0, 30, 2000005, 1, 'Ascension Reaper starter kit'),
(0, 30, 2001095, 1, 'Ascension Reaper starter kit'),
(0, 30, 6948, 1, 'Ascension Reaper starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 31 AND `Note` = 'Ascension Primalist starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 31, 2000072, 1, 'Ascension Primalist starter kit'),
(0, 31, 2000073, 1, 'Ascension Primalist starter kit'),
(0, 31, 2000074, 1, 'Ascension Primalist starter kit'),
(0, 31, 629941, 1, 'Ascension Primalist starter kit'),
(0, 31, 6948, 1, 'Ascension Primalist starter kit');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 32 AND `Note` = 'Ascension Runemaster starter kit';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 32, 2000078, 1, 'Ascension Runemaster starter kit'),
(0, 32, 2000079, 1, 'Ascension Runemaster starter kit'),
(0, 32, 2000080, 1, 'Ascension Runemaster starter kit'),
(0, 32, 629952, 1, 'Ascension Runemaster starter kit'),
(0, 32, 511017, 1, 'Ascension Runemaster starter kit'),
(0, 32, 6948, 1, 'Ascension Runemaster starter kit');
-- Deprecated baseline grants: keep spell definitions and unrelated creation rows.
DELETE FROM `playercreateinfo_spell_custom` WHERE `racemask` = 0 AND `classmask` = 16384 AND `Spell` = 804657 AND `Note` LIKE 'Ascension %';
DELETE FROM `playercreateinfo_spell_custom` WHERE `racemask` = 0 AND `classmask` = 1048576 AND `Spell` = 804331 AND `Note` LIKE 'Ascension %';
DELETE FROM `playercreateinfo_spell_custom` WHERE `racemask` = 0 AND `classmask` = 134217728 AND `Spell` = 801711 AND `Note` LIKE 'Ascension %';
COMMIT;
