-- Generated by tools/Generate-VenomancerCatalyst.py; source-only candidate.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = 800895 AND `ScriptName` = 'spell_ascension_venomancer_catalyst';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (800895, 'spell_ascension_venomancer_catalyst');
COMMIT;
