-- Generated by tools/Generate-RaidPowerBuffs.py; policy version 1.
-- Requires the reviewed Instinctual Combatant mask correction; native exclusive-highest rule.
START TRANSACTION;
DELETE FROM `spell_group` WHERE `id` = 1133;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(1133, 705070),
(1133, 567237),
(1133, 805442),
(1133, 704540),
(1133, 705156),
(1133, 806124);
DELETE FROM `spell_group_stack_rules` WHERE `group_id` = 1133;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`, `description`) VALUES
(1133, 4, 'Local CoA: strongest common raid attack and spell power buff');
COMMIT;
