-- Generated by tools/Generate-WitchHunterFlames.py; policy version1.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = -680537 AND `ScriptName` = 'spell_ascension_witch_hunter_flame_grant';
DELETE FROM `spell_script_names` WHERE `spell_id` = -802019 AND `ScriptName` = 'spell_ascension_witch_hunter_flame_grant';
DELETE FROM `spell_script_names` WHERE `spell_id` = -802140 AND `ScriptName` = 'spell_ascension_witch_hunter_flame_grant';
DELETE FROM `spell_script_names` WHERE `spell_id` = 803710 AND `ScriptName` = 'spell_ascension_witch_hunter_flame_duration';
DELETE FROM `spell_script_names` WHERE `spell_id` = 802845 AND `ScriptName` = 'spell_ascension_witch_hunter_flame_duration';
DELETE FROM `spell_script_names` WHERE `spell_id` = 803503 AND `ScriptName` = 'spell_ascension_witch_hunter_flame_duration';
DELETE FROM `spell_script_names` WHERE `spell_id` = 504779 AND `ScriptName` = 'spell_ascension_witch_hunter_flame_duration';
DELETE FROM `spell_script_names` WHERE `spell_id` = 805365 AND `ScriptName` = 'spell_ascension_witch_hunter_flame_duration';
DELETE FROM `spell_script_names` WHERE `spell_id` = 803422 AND `ScriptName` = 'spell_ascension_witch_hunter_flames_of_sin';
DELETE FROM `spell_script_names` WHERE `spell_id` = 802850 AND `ScriptName` = 'spell_ascension_witch_hunter_flame_damage';
DELETE FROM `spell_script_names` WHERE `spell_id` = 503655 AND `ScriptName` = 'spell_ascension_witch_hunter_flame_modifier_update';
DELETE FROM `spell_script_names` WHERE `spell_id` = 504890 AND `ScriptName` = 'spell_ascension_witch_hunter_flame_modifier_update';
DELETE FROM `spell_script_names` WHERE `spell_id` = 802277 AND `ScriptName` = 'spell_ascension_witch_hunter_flame_modifier_update';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(-680537, 'spell_ascension_witch_hunter_flame_grant'),
(-802019, 'spell_ascension_witch_hunter_flame_grant'),
(-802140, 'spell_ascension_witch_hunter_flame_grant'),
(803710, 'spell_ascension_witch_hunter_flame_duration'),
(802845, 'spell_ascension_witch_hunter_flame_duration'),
(803503, 'spell_ascension_witch_hunter_flame_duration'),
(504779, 'spell_ascension_witch_hunter_flame_duration'),
(805365, 'spell_ascension_witch_hunter_flame_duration'),
(803422, 'spell_ascension_witch_hunter_flames_of_sin'),
(802850, 'spell_ascension_witch_hunter_flame_damage'),
(503655, 'spell_ascension_witch_hunter_flame_modifier_update'),
(504890, 'spell_ascension_witch_hunter_flame_modifier_update'),
(802277, 'spell_ascension_witch_hunter_flame_modifier_update');
DELETE FROM `spell_proc` WHERE `SpellId` IN (92094, 803422);
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(92094, 0, 21, 1024, 0, 0, 65552, 7, 1, 0, 0, 0, 0, 100, 0, 0),
(803422, 0, 0, 0, 0, 0, 68, 1, 2, 0, 0, 4, 0, 100, 0, 0);
COMMIT;
