-- Generated by tools/Generate-TinkerOverload.py; source-only candidate.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = 707403 AND `ScriptName` = 'aura_ascension_tinker_overload';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(707403, 'aura_ascension_tinker_overload');
DELETE FROM `spell_script_names` WHERE `spell_id` = 681003 AND `ScriptName` = 'aura_ascension_tinker_extender';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(681003, 'aura_ascension_tinker_extender');
DELETE FROM `spell_proc` WHERE `SpellId` IN (707403, 681003);
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(707403, 4, 34, 0, 0, 0, 256, 1, 2, 3, 0, 0, 0, 40, 0, 0),
(681003, 0, 34, 0, 0, 0, 82176, 0, 1, 0, 0, 0, 0, 100, 0, 0);
COMMIT;
