-- Generated by Tools/Generate-AnyRaceClass.py --write; do not edit.
-- Add only absent custom-class combinations. Preserve all existing rows, stats and characters.
START TRANSACTION;
DELETE FROM `playercreateinfo` WHERE `race` = 1 AND `class` = 14;
DELETE FROM `playercreateinfo` WHERE `race` = 1 AND `class` = 17;
DELETE FROM `playercreateinfo` WHERE `race` = 1 AND `class` = 26;
DELETE FROM `playercreateinfo` WHERE `race` = 1 AND `class` = 29;
DELETE FROM `playercreateinfo` WHERE `race` = 1 AND `class` = 31;
DELETE FROM `playercreateinfo` WHERE `race` = 2 AND `class` = 15;
DELETE FROM `playercreateinfo` WHERE `race` = 2 AND `class` = 19;
DELETE FROM `playercreateinfo` WHERE `race` = 2 AND `class` = 20;
DELETE FROM `playercreateinfo` WHERE `race` = 2 AND `class` = 22;
DELETE FROM `playercreateinfo` WHERE `race` = 2 AND `class` = 26;
DELETE FROM `playercreateinfo` WHERE `race` = 2 AND `class` = 27;
DELETE FROM `playercreateinfo` WHERE `race` = 2 AND `class` = 29;
DELETE FROM `playercreateinfo` WHERE `race` = 2 AND `class` = 30;
DELETE FROM `playercreateinfo` WHERE `race` = 3 AND `class` = 13;
DELETE FROM `playercreateinfo` WHERE `race` = 3 AND `class` = 14;
DELETE FROM `playercreateinfo` WHERE `race` = 3 AND `class` = 15;
DELETE FROM `playercreateinfo` WHERE `race` = 3 AND `class` = 17;
DELETE FROM `playercreateinfo` WHERE `race` = 3 AND `class` = 20;
DELETE FROM `playercreateinfo` WHERE `race` = 3 AND `class` = 22;
DELETE FROM `playercreateinfo` WHERE `race` = 3 AND `class` = 23;
DELETE FROM `playercreateinfo` WHERE `race` = 3 AND `class` = 26;
DELETE FROM `playercreateinfo` WHERE `race` = 3 AND `class` = 29;
DELETE FROM `playercreateinfo` WHERE `race` = 3 AND `class` = 30;
DELETE FROM `playercreateinfo` WHERE `race` = 4 AND `class` = 12;
DELETE FROM `playercreateinfo` WHERE `race` = 4 AND `class` = 13;
DELETE FROM `playercreateinfo` WHERE `race` = 4 AND `class` = 16;
DELETE FROM `playercreateinfo` WHERE `race` = 4 AND `class` = 17;
DELETE FROM `playercreateinfo` WHERE `race` = 4 AND `class` = 19;
DELETE FROM `playercreateinfo` WHERE `race` = 4 AND `class` = 22;
DELETE FROM `playercreateinfo` WHERE `race` = 4 AND `class` = 23;
DELETE FROM `playercreateinfo` WHERE `race` = 4 AND `class` = 27;
DELETE FROM `playercreateinfo` WHERE `race` = 4 AND `class` = 28;
DELETE FROM `playercreateinfo` WHERE `race` = 4 AND `class` = 30;
DELETE FROM `playercreateinfo` WHERE `race` = 5 AND `class` = 13;
DELETE FROM `playercreateinfo` WHERE `race` = 5 AND `class` = 14;
DELETE FROM `playercreateinfo` WHERE `race` = 5 AND `class` = 17;
DELETE FROM `playercreateinfo` WHERE `race` = 5 AND `class` = 22;
DELETE FROM `playercreateinfo` WHERE `race` = 5 AND `class` = 26;
DELETE FROM `playercreateinfo` WHERE `race` = 5 AND `class` = 27;
DELETE FROM `playercreateinfo` WHERE `race` = 5 AND `class` = 31;
DELETE FROM `playercreateinfo` WHERE `race` = 6 AND `class` = 13;
DELETE FROM `playercreateinfo` WHERE `race` = 6 AND `class` = 14;
DELETE FROM `playercreateinfo` WHERE `race` = 6 AND `class` = 15;
DELETE FROM `playercreateinfo` WHERE `race` = 6 AND `class` = 17;
DELETE FROM `playercreateinfo` WHERE `race` = 6 AND `class` = 19;
DELETE FROM `playercreateinfo` WHERE `race` = 6 AND `class` = 20;
DELETE FROM `playercreateinfo` WHERE `race` = 6 AND `class` = 21;
DELETE FROM `playercreateinfo` WHERE `race` = 6 AND `class` = 22;
DELETE FROM `playercreateinfo` WHERE `race` = 6 AND `class` = 23;
DELETE FROM `playercreateinfo` WHERE `race` = 6 AND `class` = 28;
DELETE FROM `playercreateinfo` WHERE `race` = 6 AND `class` = 29;
DELETE FROM `playercreateinfo` WHERE `race` = 6 AND `class` = 30;
DELETE FROM `playercreateinfo` WHERE `race` = 7 AND `class` = 12;
DELETE FROM `playercreateinfo` WHERE `race` = 7 AND `class` = 13;
DELETE FROM `playercreateinfo` WHERE `race` = 7 AND `class` = 14;
DELETE FROM `playercreateinfo` WHERE `race` = 7 AND `class` = 15;
DELETE FROM `playercreateinfo` WHERE `race` = 7 AND `class` = 17;
DELETE FROM `playercreateinfo` WHERE `race` = 7 AND `class` = 18;
DELETE FROM `playercreateinfo` WHERE `race` = 7 AND `class` = 19;
DELETE FROM `playercreateinfo` WHERE `race` = 7 AND `class` = 20;
DELETE FROM `playercreateinfo` WHERE `race` = 7 AND `class` = 26;
DELETE FROM `playercreateinfo` WHERE `race` = 7 AND `class` = 27;
DELETE FROM `playercreateinfo` WHERE `race` = 7 AND `class` = 29;
DELETE FROM `playercreateinfo` WHERE `race` = 7 AND `class` = 30;
DELETE FROM `playercreateinfo` WHERE `race` = 7 AND `class` = 31;
DELETE FROM `playercreateinfo` WHERE `race` = 8 AND `class` = 14;
DELETE FROM `playercreateinfo` WHERE `race` = 8 AND `class` = 15;
DELETE FROM `playercreateinfo` WHERE `race` = 8 AND `class` = 17;
DELETE FROM `playercreateinfo` WHERE `race` = 8 AND `class` = 19;
DELETE FROM `playercreateinfo` WHERE `race` = 8 AND `class` = 22;
DELETE FROM `playercreateinfo` WHERE `race` = 8 AND `class` = 26;
DELETE FROM `playercreateinfo` WHERE `race` = 8 AND `class` = 27;
DELETE FROM `playercreateinfo` WHERE `race` = 8 AND `class` = 28;
DELETE FROM `playercreateinfo` WHERE `race` = 8 AND `class` = 32;
DELETE FROM `playercreateinfo` WHERE `race` = 10 AND `class` = 12;
DELETE FROM `playercreateinfo` WHERE `race` = 10 AND `class` = 13;
DELETE FROM `playercreateinfo` WHERE `race` = 10 AND `class` = 15;
DELETE FROM `playercreateinfo` WHERE `race` = 10 AND `class` = 29;
DELETE FROM `playercreateinfo` WHERE `race` = 10 AND `class` = 31;
DELETE FROM `playercreateinfo` WHERE `race` = 11 AND `class` = 12;
DELETE FROM `playercreateinfo` WHERE `race` = 11 AND `class` = 13;
DELETE FROM `playercreateinfo` WHERE `race` = 11 AND `class` = 15;
DELETE FROM `playercreateinfo` WHERE `race` = 11 AND `class` = 20;
DELETE FROM `playercreateinfo` WHERE `race` = 11 AND `class` = 21;
DELETE FROM `playercreateinfo` WHERE `race` = 11 AND `class` = 27;
DELETE FROM `playercreateinfo` WHERE `race` = 11 AND `class` = 29;
INSERT INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES
(1, 14, 0, 12, -8949.95, -132.493, 83.5312, 0),
(1, 17, 0, 12, -8949.95, -132.493, 83.5312, 0),
(1, 26, 0, 12, -8949.95, -132.493, 83.5312, 0),
(1, 29, 0, 12, -8949.95, -132.493, 83.5312, 0),
(1, 31, 0, 12, -8949.95, -132.493, 83.5312, 0),
(2, 15, 1, 14, -618.518, -4251.67, 38.718, 0),
(2, 19, 1, 14, -618.518, -4251.67, 38.718, 0),
(2, 20, 1, 14, -618.518, -4251.67, 38.718, 0),
(2, 22, 1, 14, -618.518, -4251.67, 38.718, 0),
(2, 26, 1, 14, -618.518, -4251.67, 38.718, 0),
(2, 27, 1, 14, -618.518, -4251.67, 38.718, 0),
(2, 29, 1, 14, -618.518, -4251.67, 38.718, 0),
(2, 30, 1, 14, -618.518, -4251.67, 38.718, 0),
(3, 13, 0, 1, -6240.32, 331.033, 382.758, 6.17716),
(3, 14, 0, 1, -6240.32, 331.033, 382.758, 6.17716),
(3, 15, 0, 1, -6240.32, 331.033, 382.758, 6.17716),
(3, 17, 0, 1, -6240.32, 331.033, 382.758, 6.17716),
(3, 20, 0, 1, -6240.32, 331.033, 382.758, 6.17716),
(3, 22, 0, 1, -6240.32, 331.033, 382.758, 6.17716),
(3, 23, 0, 1, -6240.32, 331.033, 382.758, 6.17716),
(3, 26, 0, 1, -6240.32, 331.033, 382.758, 6.17716),
(3, 29, 0, 1, -6240.32, 331.033, 382.758, 6.17716),
(3, 30, 0, 1, -6240.32, 331.033, 382.758, 6.17716),
(4, 12, 1, 141, 10311.3, 832.463, 1326.41, 5.69632),
(4, 13, 1, 141, 10311.3, 832.463, 1326.41, 5.69632),
(4, 16, 1, 141, 10311.3, 832.463, 1326.41, 5.69632),
(4, 17, 1, 141, 10311.3, 832.463, 1326.41, 5.69632),
(4, 19, 1, 141, 10311.3, 832.463, 1326.41, 5.69632),
(4, 22, 1, 141, 10311.3, 832.463, 1326.41, 5.69632),
(4, 23, 1, 141, 10311.3, 832.463, 1326.41, 5.69632),
(4, 27, 1, 141, 10311.3, 832.463, 1326.41, 5.69632),
(4, 28, 1, 141, 10311.3, 832.463, 1326.41, 5.69632),
(4, 30, 1, 141, 10311.3, 832.463, 1326.41, 5.69632),
(5, 13, 0, 85, 1676.71, 1678.31, 121.67, 2.70526),
(5, 14, 0, 85, 1676.71, 1678.31, 121.67, 2.70526),
(5, 17, 0, 85, 1676.71, 1678.31, 121.67, 2.70526),
(5, 22, 0, 85, 1676.71, 1678.31, 121.67, 2.70526),
(5, 26, 0, 85, 1676.71, 1678.31, 121.67, 2.70526),
(5, 27, 0, 85, 1676.71, 1678.31, 121.67, 2.70526),
(5, 31, 0, 85, 1676.71, 1678.31, 121.67, 2.70526),
(6, 13, 1, 215, -2917.58, -257.98, 52.9968, 0),
(6, 14, 1, 215, -2917.58, -257.98, 52.9968, 0),
(6, 15, 1, 215, -2917.58, -257.98, 52.9968, 0),
(6, 17, 1, 215, -2917.58, -257.98, 52.9968, 0),
(6, 19, 1, 215, -2917.58, -257.98, 52.9968, 0),
(6, 20, 1, 215, -2917.58, -257.98, 52.9968, 0),
(6, 21, 1, 215, -2917.58, -257.98, 52.9968, 0),
(6, 22, 1, 215, -2917.58, -257.98, 52.9968, 0),
(6, 23, 1, 215, -2917.58, -257.98, 52.9968, 0),
(6, 28, 1, 215, -2917.58, -257.98, 52.9968, 0),
(6, 29, 1, 215, -2917.58, -257.98, 52.9968, 0),
(6, 30, 1, 215, -2917.58, -257.98, 52.9968, 0),
(7, 12, 0, 1, -6240.32, 331.033, 382.758, 0),
(7, 13, 0, 1, -6240.32, 331.033, 382.758, 0),
(7, 14, 0, 1, -6240.32, 331.033, 382.758, 0),
(7, 15, 0, 1, -6240.32, 331.033, 382.758, 0),
(7, 17, 0, 1, -6240.32, 331.033, 382.758, 0),
(7, 18, 0, 1, -6240.32, 331.033, 382.758, 0),
(7, 19, 0, 1, -6240.32, 331.033, 382.758, 0),
(7, 20, 0, 1, -6240.32, 331.033, 382.758, 0),
(7, 26, 0, 1, -6240.32, 331.033, 382.758, 0),
(7, 27, 0, 1, -6240.32, 331.033, 382.758, 0),
(7, 29, 0, 1, -6240.32, 331.033, 382.758, 0),
(7, 30, 0, 1, -6240.32, 331.033, 382.758, 0),
(7, 31, 0, 1, -6240.32, 331.033, 382.758, 0),
(8, 14, 1, 14, -618.518, -4251.67, 38.718, 0),
(8, 15, 1, 14, -618.518, -4251.67, 38.718, 0),
(8, 17, 1, 14, -618.518, -4251.67, 38.718, 0),
(8, 19, 1, 14, -618.518, -4251.67, 38.718, 0),
(8, 22, 1, 14, -618.518, -4251.67, 38.718, 0),
(8, 26, 1, 14, -618.518, -4251.67, 38.718, 0),
(8, 27, 1, 14, -618.518, -4251.67, 38.718, 0),
(8, 28, 1, 14, -618.518, -4251.67, 38.718, 0),
(8, 32, 1, 14, -618.518, -4251.67, 38.718, 0),
(10, 12, 530, 3431, 10349.6, -6357.29, 33.4026, 5.31605),
(10, 13, 530, 3431, 10349.6, -6357.29, 33.4026, 5.31605),
(10, 15, 530, 3431, 10349.6, -6357.29, 33.4026, 5.31605),
(10, 29, 530, 3431, 10349.6, -6357.29, 33.4026, 5.31605),
(10, 31, 530, 3431, 10349.6, -6357.29, 33.4026, 5.31605),
(11, 12, 530, 3526, -3961.64, -13931.2, 100.615, 2.08364),
(11, 13, 530, 3526, -3961.64, -13931.2, 100.615, 2.08364),
(11, 15, 530, 3526, -3961.64, -13931.2, 100.615, 2.08364),
(11, 20, 530, 3526, -3961.64, -13931.2, 100.615, 2.08364),
(11, 21, 530, 3526, -3961.64, -13931.2, 100.615, 2.08364),
(11, 27, 530, 3526, -3961.64, -13931.2, 100.615, 2.08364),
(11, 29, 530, 3526, -3961.64, -13931.2, 100.615, 2.08364);
COMMIT;
