-- Generated by Tools/Generate-LocalEnchantmentLevelScripts.py --write; do not hand-edit.
-- Removes only player-level gates on two apply spells and the Minor Mount Speed self helper.
-- Preserve Blade Ward/Blood Draining proc mechanics and Minor Mount Speed lifecycle links.
-- NEW migration. The normal updater must stop on errors; never use mysql --force.
CREATE TEMPORARY TABLE `_local_enchantment_level_scripts_v3_guard` (`id` INT NOT NULL PRIMARY KEY) ENGINE=InnoDB;
DELETE FROM `_local_enchantment_level_scripts_v3_guard` WHERE `id` = 1;
INSERT INTO `_local_enchantment_level_scripts_v3_guard` (`id`) VALUES (1);
START TRANSACTION;
SET @local_enchant_scripts_count = (SELECT COUNT(*) FROM `spell_script_names`
WHERE ABS(`spell_id`) IN (13927,59917,64440,64441,64568,64579));
SET @local_enchant_scripts_keep = (SELECT COUNT(*) FROM `spell_script_names`
WHERE (`spell_id` = 64440 AND BINARY `ScriptName` = BINARY 'spell_gen_blade_warding')
OR (`spell_id` = 64568 AND BINARY `ScriptName` = BINARY 'spell_item_blood_draining_enchant'));
SET @local_enchant_scripts_remove = (SELECT COUNT(*) FROM `spell_script_names`
WHERE (`spell_id` IN (64441,64579) AND BINARY `ScriptName` = BINARY 'spell_gen_proc_above_75')
OR (`spell_id` = 59917 AND BINARY `ScriptName` = BINARY 'spell_gen_disabled_above_70'));
SET @local_enchant_links_count = (SELECT COUNT(*) FROM `spell_linked_spell`
WHERE ABS(`spell_trigger`) = 13927);
SET @local_enchant_links_keep = (SELECT COUNT(*) FROM `spell_linked_spell`
WHERE (`spell_trigger` = -13927 AND `spell_effect` = -59917 AND `type` = 0)
OR (`spell_trigger` = 13927 AND `spell_effect` = 59917 AND `type` = 1));
SET @local_enchant_scripts_allowed = @local_enchant_scripts_keep = 2
AND @local_enchant_links_count = 2 AND @local_enchant_links_keep = 2 AND
((@local_enchant_scripts_count = 5 AND @local_enchant_scripts_remove = 3) OR
(@local_enchant_scripts_count = 2 AND @local_enchant_scripts_remove = 0));
DELETE FROM `_local_enchantment_level_scripts_v3_guard` WHERE `id` <> 1;
INSERT INTO `_local_enchantment_level_scripts_v3_guard` (`id`) SELECT 1 WHERE NOT @local_enchant_scripts_allowed;
DELETE FROM `spell_script_names` WHERE @local_enchant_scripts_allowed AND
((`spell_id` IN (64441,64579) AND BINARY `ScriptName` = BINARY 'spell_gen_proc_above_75')
OR (`spell_id` = 59917 AND BINARY `ScriptName` = BINARY 'spell_gen_disabled_above_70'));
SET @local_enchant_scripts_after = (SELECT COUNT(*) FROM `spell_script_names`
WHERE ABS(`spell_id`) IN (13927,59917,64440,64441,64568,64579));
DELETE FROM `_local_enchantment_level_scripts_v3_guard` WHERE `id` <> 1;
INSERT INTO `_local_enchantment_level_scripts_v3_guard` (`id`) SELECT 1 WHERE @local_enchant_scripts_after <> 2;
COMMIT;
DROP TEMPORARY TABLE `_local_enchantment_level_scripts_v3_guard`;
