-- Generated by tools/Generate-RangerInstinctualCombatant.py; policy version 1.
-- Requires the reviewed native three-charge metadata correction.
START TRANSACTION;
DELETE FROM `spell_proc` WHERE `SpellId` = 707319;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(707319, 0, 27, 16, 0, 0, 16, 4, 1, 0, 0, 3, 0, 100, 0, 0);
COMMIT;
