-- Generated by tools/Generate-TinkerRockadier.py; policy version 1.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` = 801827 AND `ScriptName` = 'aura_ascension_tinker_rockadier';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(801827, 'aura_ascension_tinker_rockadier');
DELETE FROM `spell_proc` WHERE `SpellId` = 801827;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(801827, 0, 34, 0, 0, 0, 256, 1, 2, 3, 2, 0, 0, 100, 0, 0);
COMMIT;
