-- Generated by tools/Generate-RangerUnderhanded.py; policy version 1.
-- Pair with the reviewed Underhanded coefficient conversions and Skullpiercer scaling script.
START TRANSACTION;
DELETE FROM `spell_bonus_data` WHERE `entry` = 500073;
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(500073, 0, 0, 0, 0.25, 'Local Ranger: Serrated Shot explicit RAP per tick');
COMMIT;
