-- Generated by tools/Generate-RangerRustyShiv.py; policy version 1.
-- Deploy atomically with AscensionRangerDamage.cpp and the reviewed client text.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE (`spell_id` = 561315 AND `ScriptName` = 'spell_ascension_ranger_rusty_shiv') OR (`spell_id` = 681459 AND `ScriptName` = 'spell_ascension_ranger_rusty_shiv_damage');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(561315, 'spell_ascension_ranger_rusty_shiv'),
(681459, 'spell_ascension_ranger_rusty_shiv_damage');
DELETE FROM `spell_proc` WHERE `SpellId` = 561315;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(561315, 0, 0, 0, 0, 0, 1048576, 0, 0, 0, 2, 2, 0, 100, 0, 0);
COMMIT;
