-- Generated by tools/Generate-RangerAssaultDamage.py; policy version 1.
-- Main Assault damage only; hidden Assaulted mechanics remain separately reviewed.
START TRANSACTION;
DELETE FROM `spell_bonus_data` WHERE `entry` = 803108;
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(803108, 0, 0, 1, 0, 'Local Ranger: Assault explicit melee AP; native weapon contribution retained');
DELETE FROM `spell_script_names` WHERE `spell_id` = -803108 AND `ScriptName` = 'spell_ascension_ranger_assault';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(-803108, 'spell_ascension_ranger_assault');
COMMIT;
